// Config-driven codegen for the Asset Reloader pipeline.
//
// Reads <root>/asset-reloader.config.json (all keys optional; defaults below),
// then on each run:
//   1. (re)writes the asset/resource list from <modelsDir>/manifest.json,
//   2. scaffolds a per-model class for any NEW model (never overwrites edits),
//   3. (re)writes the generated model registry.
//
// Run manually:  node scripts/asset-codegen.mjs
// Or automatically via vite-plugin-asset-reloader.mjs.

import fs from "node:fs";
import path from "node:path";

const DEFAULTS = {
  publicDir: "public",
  modelsDir: "public/models",
  texturesDir: "public/textures",
  assetsFile: "src/Experience/Utils/assets.js", // set null to skip
  worldDir: "src/Experience/World",
  registryFile: "src/Experience/World/models.generated.js",
  template: null, // path to a custom per-model class template
};

const GEN_HEADER = "// AUTO-GENERATED by asset-reloader — do not edit by hand.\n";

// Placeholders: {{className}} {{key}} {{file}}
const DEFAULT_TEMPLATE = `import * as THREE from "three/webgpu";
import { Experience } from "../Experience";

export class {{className}} {
  constructor() {
    this.experience = Experience.getInstance();
    this.model = this.experience.resources.items.{{key}}.scene;

    this.init();
  }

  init() {
    this.model.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });

    this.experience.scene.add(this.model);
  }

  resize() {}

  update() {}

  destroy() {}
}
`;

export function loadConfig(root) {
  const file = path.join(root, "asset-reloader.config.json");
  let cfg = {};
  if (fs.existsSync(file)) {
    try {
      cfg = JSON.parse(fs.readFileSync(file, "utf-8"));
    } catch (err) {
      throw new Error(`Invalid asset-reloader.config.json: ${err.message}`);
    }
  }
  return { ...DEFAULTS, ...cfg };
}

function pascalCase(base) {
  const parts = base.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  let name = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join("");
  if (/^[0-9]/.test(name)) name = "Model" + name; // valid JS identifier
  return name || "Model";
}

function camelCase(base) {
  const p = pascalCase(base);
  return p[0].toLowerCase() + p.slice(1);
}

function toPosix(p) {
  return p.split(path.sep).join("/");
}

function listModels(modelsDir) {
  const manifestPath = path.join(modelsDir, "manifest.json");
  let files;
  if (fs.existsSync(manifestPath)) {
    files = JSON.parse(fs.readFileSync(manifestPath, "utf-8")).models ?? [];
  } else if (fs.existsSync(modelsDir)) {
    files = fs.readdirSync(modelsDir).filter((f) => f.toLowerCase().endsWith(".glb"));
  } else {
    files = [];
  }
  return files.map((file) => {
    const base = file.replace(/\.glb$/i, "");
    return { file, base, key: camelCase(base), className: pascalCase(base) };
  });
}

function renderTemplate(tpl, m) {
  return tpl
    .replaceAll("{{className}}", m.className)
    .replaceAll("{{key}}", m.key)
    .replaceAll("{{file}}", m.file);
}

export function generate(root = process.cwd()) {
  const cfg = loadConfig(root);
  const modelsDir = path.resolve(root, cfg.modelsDir);
  const worldDir = path.resolve(root, cfg.worldDir);
  const models = listModels(modelsDir);

  fs.mkdirSync(worldDir, { recursive: true });

  // 1. asset / resource list (optional)
  if (cfg.assetsFile) {
    const assetsFile = path.resolve(root, cfg.assetsFile);
    const publicDir = path.resolve(root, cfg.publicDir);
    const webBase = "/" + toPosix(path.relative(publicDir, modelsDir));
    const entries = models
      .map(
        (m) =>
          `  {\n    name: "${m.key}",\n    type: "glbModel",\n    path: "${webBase}/${m.file}",\n  },`,
      )
      .join("\n");
    fs.mkdirSync(path.dirname(assetsFile), { recursive: true });
    fs.writeFileSync(assetsFile, `${GEN_HEADER}export default [\n${entries}\n];\n`);
  }

  // 2. per-model class scaffolds (never overwrite existing files)
  let tpl = DEFAULT_TEMPLATE;
  if (cfg.template) {
    const tp = path.resolve(root, cfg.template);
    if (fs.existsSync(tp)) tpl = fs.readFileSync(tp, "utf-8");
  }
  const created = [];
  for (const m of models) {
    const file = path.join(worldDir, `${m.className}.js`);
    if (fs.existsSync(file)) continue;
    fs.writeFileSync(file, renderTemplate(tpl, m));
    created.push(m.className);
  }

  // 3. generated registry
  const registryFile = path.resolve(root, cfg.registryFile);
  const regDir = path.dirname(registryFile);
  const importPath = (m) => {
    let rel = toPosix(path.relative(regDir, path.join(worldDir, `${m.className}.js`)));
    if (!rel.startsWith(".")) rel = "./" + rel;
    return rel;
  };
  const imports = models
    .map((m) => `import { ${m.className} } from "${importPath(m)}";`)
    .join("\n");
  const list = models.map((m) => `  ${m.className},`).join("\n");
  fs.mkdirSync(regDir, { recursive: true });
  fs.writeFileSync(
    registryFile,
    `${GEN_HEADER}${imports}\n\nexport const modelClasses = [\n${list}\n];\n`,
  );

  return { count: models.length, created, keys: models.map((m) => m.key) };
}

if (process.argv[1] && process.argv[1].endsWith("asset-codegen.mjs")) {
  const r = generate(process.cwd());
  console.log(
    `[asset-reloader] ${r.count} model(s): ${r.keys.join(", ") || "(none)"}` +
      (r.created.length ? ` | scaffolded: ${r.created.join(", ")}` : ""),
  );
}
